apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: zg9kwsxoo-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/zg9kwsxoo-java-springboot-gitops